### ISSUE TITLE
When using the Gemini 1.5 pro model, the program encounters an error.

### ISSUE THREAD

**Issue by voiweb** [qingyanbaby/poe_2_openai#1]
model_mapping = {
"gpt-3.5-turbo": "Gemini-1.5-Pro",
}

Have a try, and what caused this problem?

**Comment by voiweb** [comment]
And then what is the QPS limit for the poe api?

**Comment by qingyanbaby** [comment]
```env
MODEL_MAPPING='{
    "gpt-3.5-turbo": "Gemini-1.5-Pro",
    "gpt-4o": "GPT-4o",
    "gpt-4-turbo": "GPT-4-Turbo"
}'
```
My configuration is as mentioned above, and I have tried it. There is no problem with the Gemini-1.5-Pro robot. As for the specific rate limiting, I am not sure. The official will deduct points according to the usage, and once the points are used up, it will no longer be possible to make calls.
![1720679810521](https://github.com/qingyanbaby/poe_2_openai/assets/114038938/0a2fbf66-06a2-4848-a59c-3ddde760699b)

**Comment by qingyanbaby** [comment]
You need to use the latest code and then configure the environment variable `MODEL_MAPPING` in the .env file or system environment variables. The environment variable is in uppercase.

**Comment by voiweb** [comment]
<img width="1216" alt="image" src="https://github.com/qingyanbaby/poe_2_openai/assets/19694332/4bcf47e6-1230-4c97-a902-b3911b83e893">
**Here is my debug log. It works fine with other models, but when using Gemini, this error occurs, which is very confusing. And regardless of whether I use Docker or directly use the python command, the error output is the same**
@qingyanbaby

**Comment by qingyanbaby** [comment]
@ # 149817d
Yes. An error occurs when using the API parameter `stream: false`. I have already fixed it. Please pull the latest code and try again.
@voiweb
