### ISSUE TITLE
Poe账号不充值可以用吗?

### ISSUE THREAD

**Issue by gaoconggit** [qingyanbaby/poe_2_openai#12]
前几天用得很爽的。这两天开始用不了了

**Comment by gaoconggit** [comment]
![image](https://github.com/user-attachments/assets/22fca7cc-ca85-4d5a-a5dd-1c94fbf60436)
---
看起来是要充值用户才可以用

**Comment by qingyanbaby** [comment]
订阅才能用，很多模型，订阅用户才能调用，免费用户额度也不多
