### ISSUE TITLE
[Feature request] Proxy support

### ISSUE THREAD

**Issue by chenxuuu** [qingyanbaby/poe_2_openai#2]
Some area can't connect poe directly, need http/socks proxy function.
Is there some way to use proxy?

**Comment by qingyanbaby** [comment]
Okay, I will add the proxy function this week.

**Comment by qingyanbaby** [comment]
@chenxuuu 
The proxy support has been added. Please download the latest code and give it a try.
640db6efbbd6bcf1bb2359c457ebbf330e2b1512

**Comment by chenxuuu** [comment]
perfect
