### ISSUE TITLE
`route_chat.py` line 28出错

### ISSUE THREAD

**Issue by Luo-hongyi** [qingyanbaby/poe_2_openai#5]
```
body = await request.json()
```

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Luo-hongyi** [comment]
另外，NextChat会用`OPTIONS`发出访问

**Comment by qingyanbaby** [comment]
报错的是哪个模型？nextchat用的网页端吗？网页端会有跨域问题。后续我加一下跨域处理

**Comment by qingyanbaby** [comment]
b672257d673180ae7447a979f4be93c9d1d2b372
