### ISSUE TITLE
大佬能不能增加 api_key 校验，或者直接用客户端传过来的 api-key 给 poe 那边？

### ISSUE THREAD

**Issue by ifastcc** [qingyanbaby/poe_2_openai#8]

**Comment by qingyanbaby** [comment]
现在的逻辑是，env配置里`CUSTOM_TOKEN`是自定义校验token，`SYSTEM_TOKEN`是poe的token。当调用方传上来的token和`CUSTOM_TOKEN`一致时，会传`SYSTEM_TOKEN`给poe，不一致时，直接传客户提交的token给poe。应该已经符合你的需求

**Comment by ifastcc** [comment]
谢谢大佬解答
